### PR TITLE
Introduce sed command

### PR DESCRIPTION
**Pull request by karitham**
Hi,

This pull request introduces the sed command, together with a few tests

I also cleaned up the struct fields alignment.

Tell me if there's anything to clean up

### CODE REVIEW

**Comment by insomnimus** [comment]
Thanks for the contribution!

I don't intend to add sub-commands to gerp for a number of reasons:

-  They may actually be search terms
-  If gerp went that route, there wouldn't be many sub-commands (1 or 2 more perhaps) which sort of kills the purpose
-  I don't want to move too far away from the good old grep

However I love the idea, so how about this:

We move the functionality to a new command line option: `--replace=<regexp>`.

This would allow for the search pattern to stay unchanged, for example an invocation might look like this:

`gerp 'greetings|hi\s(\w+)' --replace='hello $1'`

Let me know what you think, I'm open to ideas.

**Comment by karitham** [comment]
That makes a lot of sense, I added it as a subcommand since that's my usual practice, but having it as just a flag might be a lot better

Thanks for the feedback

**Comment by karitham** [comment]
It looks to me like the current code is convoluted and not really scalable, and adding again another flag will mess things up more,

I'm not gonna work on adding the flag since I can't spend that much time on it, I'll just close the PR and keep my branch if that's okay with you.

**Comment by insomnimus** [comment]
No problem!
I agree there's some refactoring to do, mainly because the arg parsing was changed from manual to urfave/cli almost as an afterthought (i decided i wanted shell completions, so yeah).

I'll refactor the entire code base and turn it into something scalable when i get the time.

I hope to see your contributions once the code is cleaner!

**Pull request closed without merging**
